### PR TITLE
Docker-compose

### PR DESCRIPTION
**Pull request by rossandrews**
Working getting my development setup again and was interested in the docker approach. Used docker-compose to build and deploy the latest code and a MQTT broker to output use. You can connect to the MQTT broker like a regular broker with an external MQTT browser to watch the values.

Change the mpp-solar config in docker/mpp-solar.conf. Change the command run in docker-compose.yaml entrypoint section.

command: 
docker-compose up --build

### CODE REVIEW

**Comment by jblance** [comment]
I see you are pulling from the source repo and making it an editable install - is this intended for development purposes?
Would installing the latest pypi package be better?

**Comment by rossandrews** [comment]
Added a development Dockerfile and compose yaml. Command to run docker compose for development is:
docker compose -f docker-compose.development.yaml up --build

I could probably find a way to move this docker config into the docker folder.

**Comment by jblance** [comment]
you can also use the makefile to add shortcuts to more complex commands - allowing `make docker-up` type commands to substitute for `docker compose -f docker-compose.development.yaml up --build` (or more)

**Comment by jblance** [comment]
is this ready for merging?

**Comment by rossandrews** [comment]
As long as you are happy with it.

**Pull request merged**
