### PR TITLE
Update json_mqtt.py

### PR DESCRIPTION
**Pull request by sante85**
Add tag information to topic

### CODE REVIEW

**Comment by rossandrews** [comment]
Good catch and bugfix, could you add a unit test? There are several format unit tests you can use as examples, like test_format_htmltable.py

**Comment by sante85** [comment]
for me is difficult now. You have a suggests for speedup this phase?

Il giorno ven 20 ott 2023 alle ore 18:50 Ross Andrews <
***@***.***> ha scritto:

**Comment by sante85** [comment]
When do you think to make a release of python Pi repository?

Il dom 22 ott 2023, 03:58 John Blance ***@***.***> ha scritto:

**Comment by jblance** [comment]
Should be there now

**Pull request merged**
